services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  subscriber:
    build:
      context: ..                       # Apunta a la raíz del proyecto (donde está el pom.xml y src)
      dockerfile: src/subscriber/Dockerfile     # Ruta al Dockerfile relativa al contexto
    container_name: java-subscriber
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/iiss2026
      - DB_USER=postgres
      - DB_PASSWORD=root
    depends_on:
      - mosquitto
      - postgres
    restart: unless-stopped

  eventgenerator:
    build:
      context: ..
      dockerfile: src/eventGenerator/Dockerfile
    container_name: event-generator
    depends_on:
      - mosquitto
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=iiss2026
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:


